[project]
name = "scandir-rs"
version = "2.5.1"
authors = [{ name = "Martin Bammer", email = "mrbm74@gmail.com" }]
description = "A Rust library for parsing and generating A2L files."
dependencies = []
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Rust",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "License :: OSI Approved :: MIT License",
]

[build-system]
requires = [
    "setuptools>=41.0.0",
    "wheel",
    "setuptools_rust>=0.10.2",
    "toml",
    "maturin>=0.12",
]
build-backend = "maturin"

[tool.maturin]
manylinux = "off"
strip = true
