[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=x86-64-v3", "-Zshare-generics=n"]

[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "target-cpu=x86-64-v3", "-Zshare-generics=n"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-cpu=x86-64-v3", "-Zshare-generics=n"]
linker = "rust-lld.exe"
